[build]
  command   = "npm run build"
  publish   = "dist/public"         # keep your current publish folder
  functions = "netlify/functions"   # <— add this

# 1) Send all /api/* requests to the serverless function
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/api/:splat"
  status = 200
  force  = true

# 2) SPA fallback (must be AFTER the /api/* rule)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

